-name: install apache service
 host: webserver1
 become: yes
 tasks:
  -name: install httpd package
   yum:
    name: httpd
    state : latest
  -name: start httpd service
   service:
    name: httpd
    state: started
    enabled: yes
   name: Update the default landing page
      copy:
        content: "<h1>You Are On Webserver 1!</h1>"
        dest: /var/www/html/index.html
        owner: apache
        group: apache
        mode: '0644'